[package]
name = "boundless-cli"
version = "5.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "boundlessctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tonic.workspace = true

app-services = { path = "../app-services" }
control-plane-client = { path = "../control-plane-client" }
ipc-api = { path = "../ipc-api" }
core-clipboard = { path = "../core-clipboard" }
core-discovery = { path = "../core-discovery" }

[target.'cfg(windows)'.dependencies]
platform-windows = { path = "../platform-windows" }
windows-service = "0.8.0"
