[package]
name = "ipc-api"
version = "5.0.16"
edition.workspace = true
license.workspace = true

[dependencies]
core-input = { path = "../core-input" }
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
protoc-bin-vendored.workspace = true
tonic-prost-build.workspace = true
